import logging
import os
from pathlib import Path
import shutil
import subprocess
import time
import typing
from typing import Union
import warnings

import dclab
import h5py
import numpy as np
from torch.utils.data import DataLoader

from .images import correct_background
from ..io import load_ml_score_to_int
from ..models import OneModel
from dcml.utils.data import create_single_dataset
from dcml.predict import predict

logger = logging.getLogger(__name__)


class DatasetNotLabeledException(Exception):
    pass


class NoLabeledEventsInDatasetWarning(Warning):
    pass


class EmptyLabeledDatasetNotExported(Warning):
    pass


def get_predictions(ds_path: Path,
                    model: OneModel,
                    batch_size: int,
                    num_workers: int,
                    device: str,
                    mean:float =None,
                    std:float = None,
                    brightness_factor:float | None = None
                    ) -> np.ndarray:
    """
    Get predictions from a trained model on a dataset.

    Parameters
    ----------
    ds_path: Path
        The path to the RTDC-dataset.
    model: BaseModel
        The trained model for making predictions.
    batch_size: int
        The batch size to use when processing the dataset.
    num_workers: int
        The number of parallel workers for data loading.
    device: str
        The device on which to perform model inference (e.g., 'cuda', 'cpu').
    mean: mean of the dataset to be used for normalization. If None the mean saved within
                      the model, which was used for training will be used
    std: standard deviation of the dataset to be used for normalization. If None the standard deviation saved within
                      the model, which was used for training will be used

    brightness_factor: if not None, it will be used to correct brightenss of the images by multiplying it with the images

    Returns
    -------
    np.ndarray
        An array containing the predictions generated by the model.

    Example
    -------
    >>> predictions = get_predictions(
    ...     ds_path='/path/to/dataset',
    ...     model=my_trained_model,
    ...     batch_size=64,
    ...     num_workers=4,
    ...     device='cuda'
    ... )
    """

    dataset_params = model.params["create_dataset"]
    class_label_dict = model.params["create_trainer"]["class_label_dict"]

    if mean is None:
        mean = dataset_params['mean']

    if std is None:
        std = dataset_params['std']

    # if p99 is None:
    #     p99 = dataset_params['p99']

    # if compute_mean_std:  # compute statistics from the dataset
    #     mean = None
    #     std = None
    # else:  # use the same statistics as was used for training
    #     mean = dataset_params['mean']
    #     std = dataset_params['std']

    MTL_mode = bool(getattr(model.model, 'num_heads', False)) == True

    dataset = create_single_dataset(hdf5_path=ds_path,
                                    required_data={"image": "image"},
                                    correct_background=False,
                                    crop_size=dataset_params["crop_size"],
                                    mean=mean,
                                    std=std,
                                    MTL=MTL_mode,
                                    brightness_factor=brightness_factor
                                    )

    dataloader = DataLoader(dataset,
                            batch_size=batch_size,
                            shuffle=False,
                            num_workers=num_workers)

    # Apply model
    # logger.info(f"Predicting Cells -- Start Time: {time.ctime()}")

    _, prediction_probs, _, _ = predict(model.model, dataloader, criterion=None, device=device, class_label_dict=class_label_dict)
    prediction_probs = np.array(prediction_probs, dtype=np.float64)

    return prediction_probs

# TODO can be combined with predict_cell_type()
def predict_cell_type_with_basin(path_in: Union[str, Path],
                                 path_out: Union[str, Path],
                                 # model_path: Union[str, Path],
                                 # model_name: str = "",
                                 model: OneModel = None,
                                 # mlflow: bool = False,
                                 device: str = 'cuda',
                                 num_workers: int = 8,
                                 batch_size: int = 2000,
                                 mean=None,
                                 std=None,
                                 brightness_factor=None
                                 ):
    """Store cell predictions on dataset in external file using basins

    This function assumes that `image_bg` was computed for the datasets
    beforehand.

    Parameter
    ---------
    path_in:
        Path of RTDC file for which cell prediction will be computed. This
        function requires "image_bg" to be computed beforehand (e.g. via
        dcevent)
    path_out:
        Save path of RTDC file only containing cell predictions. It will
        use the file in `path_in` as basin.
    model: model to be used for prediction
    device: {'cuda', 'cpu'}, optional
    num_workers: int, optional
        Count of threads used for Dataloader to load batches
    batch_size
        Batch size used for model inference.

    Note:
        This prediction-function creates basins and will not reference
        potientially existing `ml_score`-features in these basins. It will only
        contain its own predicten `ml_score`-features and therefore it is not
        necessary to clean up previous predictions.

    Raises:
        FileExistsError
            Raises error if `path_out` already exists
    """
    path_in = Path(path_in)
    path_out = Path(path_out)

    if path_out.exists():
        raise FileExistsError(f"File already exists at Path: '{path_out}'!")

    # logger.info(f"Cell Prediction of {path_in} -- Start Time: {time.ctime()}")
    # logger.info(f"Number of Workers: {num_workers}")
    # logger.info(f"Batch size: {batch_size}")

    # model = OneModel(model_path=model_path, device=device, model_name=model_name, mlflow=mlflow)

    logger.info(f"Cell Prediction in {path_in} -- Start Time: {time.ctime()}")
    prediction_probs = get_predictions(ds_path=path_in,
                                       model=model,
                                       batch_size=batch_size,
                                       num_workers=num_workers,
                                       device=device,
                                       mean=mean,
                                       std=std,
                                       brightness_factor=brightness_factor)

    logger.info(f"Cell Prediction -- End Time: {time.ctime()}")

    # prediction_probs_old = get_predictions_old(ds_path=path_in,
    #                                    model=model,
    #                                    batch_size=batch_size,
    #                                    num_workers=num_workers,
    #                                    device=device)

    # Write prediction to dataset
    logger.info("Writing Predictions to RTDC-Dataset...")
    with dclab.RTDCWriter(path_out, mode="reset") as writer, \
            dclab.new_dataset(path_in) as ds_in:

        # Write predictions to new dataset
        for idx, feat in enumerate(model.feature_names):
            writer.store_feature(feat, prediction_probs[:, idx])

        # Write Metadata to new dataset
        meta = dict(ds_in.config)
        meta.pop("filtering")
        writer.store_metadata(meta)

        basin_feats = [el for el in ds_in.features if "ml_" not in el]
        writer.store_basin(basin_name="segmentation_and_features",
                           basin_type="file",
                           basin_format="hdf5",
                           basin_locs=[path_in.resolve()],
                           basin_feats=basin_feats)

    # logger.info(f"Cell Prediction of {path_in} -- End Time: {time.ctime()}")


def predict_cell_type(path_in: Union[str, Path],
                      path_out: Union[str, Path],
                      # model_path: Union[str, Path],
                      # model_name: str = "",
                      model: OneModel = None,
                      # mlflow: bool = False,
                      device: str = 'cuda',
                      num_workers: int = 8,
                      batch_size: int = 2000,
                      cleanup_predictions: bool = True,
                      mean:float | None = None,
                      std:float | None = None,
                      brightness_factor:float | None = None
                      ):
    """Apply Cell Prediction on Dataset using torch NNs

    This function assumes that `image_bg` was computed for the datasets
    beforehand.

    Parameter
    ---------
    path_in:
        Path of RTDC file for which cell prediction will be computed. This
        function requires "image_bg" to be computed beforehand (e.g. via
        dcevent)
    path_out:
        Save path of RTDC file containing cell predictions
    model:
    device: {'cuda', 'cpu'}, optional
    num_workers: int, optional
        Count of threads used for Dataloader to load batches
    batch_size
        Batch size used for model inference.
    cleanup_predictions: bool, optional
        Set to True if you want to cleanup previous predictions.
        This will delete ALL previous predictions or any feature which
        starts with "ml_score_". Caution:

    Warnings:
    ------

    Setting 'cleanup_predictions' to True can lead to OSErrors, such as
    'double free or corruption (out)' or 'free() invalid pointer'!
    Currently the only workaround is not using datasets with pre existing
    predictions. This error seems to occur in
        ```
        subprocess.call(['h5repack'] + [str(path_out), path_out_tmp])`
        shutil.move(path_out_tmp, str(path_out))
        ```
    """
    path_in = Path(path_in)
    path_out = Path(path_out)
    # logger.info(f"Cell Prediction of {path_in} -- Start Time: {time.ctime()}")

    # Copy File to "path_out"-path
    logger.info(f"Copying {path_in} file to {path_out}")
    if not (path_in.resolve() == path_out.resolve()):
        shutil.copyfile(path_in, path_out)

    # The following assumes that there was already an RT-DC file at
    # path_out (before background correction) and that it contains ml_scores
    if cleanup_predictions:  # TODO this part fails to work properly when running in sbatch mode???
        logger.info("cleanup_predictions")
        with h5py.File(path_out, "a") as hf:
            features = list(hf["events"].keys())
            for feat in features:
                if feat.startswith("ml_score_"):
                    del hf["events"][feat]

        # To reclaim the free storage, it is necessary to repack the hdf5-file
        path_out_tmp = str(path_out) + '.tmp'
        subprocess.call(['h5repack'] + [str(path_out), path_out_tmp])
        shutil.move(path_out_tmp, str(path_out))

    # Setup (order is important and has to correspond to the target order
    # of the model)
    # logger.info(f"Number of Workers: {num_workers}")
    # logger.info(f"Batch size: {batch_size}")

    # Model Instantiation
    # model = OneModel(model_path=model_path, device=device, model_name=model_name, mlflow=mlflow)

    # Now work on file in "path_out"-path:
    # Load dataset as torch.dataset
    # prediction_probs = _get_predictions(ds_path=path_in,
    #                                     model=model,
    #                                     batch_size=batch_size,
    #                                     num_workers=num_workers,
    #                                     device=device)

    logger.info(f"Cell Prediction in {path_in} -- Start Time: {time.ctime()}")
    prediction_probs = get_predictions(ds_path=path_in,
                                       model=model,
                                       batch_size=batch_size,
                                       num_workers=num_workers,
                                       device=device,
                                       mean=mean,
                                       std=std,
                                       brightness_factor=brightness_factor)

    logger.info(f"Cell Prediction -- End Time: {time.ctime()}")

    # Write prediction to dataset
    logger.info("Writing Predictions to RTDC-Dataset...")
    with dclab.rtdc_dataset.RTDCWriter(path_out) as writer:
        for idx, fn in enumerate(model.feature_names):
            writer.store_feature(fn, prediction_probs[:, idx])

# # TODO Do I need this function? It is currently only used in update_prediction_of_dir() which is not used anywhere else.
# def update_prediction(path_in,
#                       # model_path,
#                       # model_name = "",
#                       model: OneModel = None,
#                       # mlflow: bool = False,
#                       device: str = 'cuda',
#                       num_workers: int = 16,
#                       mean=None,
#                       std=None,
#                       brightness_factor=None):
#     """Update predictions of file given by `path_in`
#
#     Wraps around `predict_cell_type`.
#
#     Parameter
#     ---------
#     path_in:
#         Path of RTDC file for which cell prediction will be updated
#     model_path:
#         Path to model for general cell type prediction or run id string if mlflow=True
#     model_name: name of the model in mlflow repository if mlflow=True
#     device: {'cuda', 'cpu'}, optional
#     num_workers: int, optional
#         Count of threads used for Dataloader to load batches
#     """
#     predict_cell_type(path_in=path_in,
#                       path_out=path_in,  # note path_out is set to path_in
#                       # model_path=model_path,
#                       # model_name=model_name,
#                       model=model,
#                       # mlflow=mlflow,
#                       device=device,
#                       num_workers=num_workers,
#                       cleanup_predictions=True,
#                       mean=mean,
#                       std=std,
#                       brightness_factor=brightness_factor)


def apply_prediction_to_dir(path_in: Union[str, Path],
                            path_out: Union[str, Path],
                            model_path: Union[str, Path],
                            model_name: str = "",
                            # mlflow: bool = False,
                            device: str = 'cuda',
                            num_workers: int = 16,
                            compute_locally: bool = False,
                            cleanup_predictions: bool = True,
                            with_basin: bool = False,
                            mean=None,
                            std=None,
                            brightness_factor=None):

    # TODO should the code in this subfunction be moved into directly to apply_prediction_to_dir?
    def process_file(src, dst, with_basin):
        if dst.exists():
            # TODO add suffix and continue processing
            logger.info(f"{dst} already exists!!! Did not Copy or Process!")
            return False
        # if src.suffix == '.rtdc':
            # logger.info(f"Processing file: {src.absolute()}")
        if compute_locally:  # TODO do I need this?
            # Setting up Path
            src_tmp = Path("tmp_orig.rtdc")
            dst_tmp = Path("tmp_bg_pred.rtdc")
            # copy data from src to local
            shutil.copy(src, src_tmp)
        else:
            src_tmp = src
            dst_tmp = dst

        # apply processing script
        if with_basin:
            predict_cell_type_with_basin(path_in=src_tmp,
                                         path_out=dst_tmp,
                                         # model_path=model_path,
                                         # model_name=model_name,
                                         model=model,
                                         device=device,
                                         num_workers=num_workers,
                                         # mlflow=mlflow,
                                         mean=mean,
                                         std=std,
                                         brightness_factor=brightness_factor
                                         )
        else:
            # apply processing script
            predict_cell_type(path_in=src_tmp,
                              path_out=dst_tmp,
                              # model_path=model_path,
                              # model_name=model_name,
                              model=model,
                              device=device,
                              num_workers=num_workers,
                              # mlflow=mlflow,
                              cleanup_predictions=cleanup_predictions,
                              mean=mean,
                              std=std,
                              brightness_factor=brightness_factor
                              )

        # copy data from local to dst
        if compute_locally:  # TODO do I need this?
            shutil.copyfile(src=dst_tmp, dst=dst)
            src_tmp.unlink()
            dst_tmp.unlink()
        # else: # TODO do I need this?
        #     shutil.copyfile(src=src, dst=dst)

    # TODO used in process_file as global - bad style
    model = OneModel(model_path=model_path, device=device, model_name=model_name)

    path_in = Path(path_in)
    path_out = Path(path_out)

    rel_in_files = [os.path.relpath(el, path_in) for el in path_in.rglob("*.rtdc") if el.is_file()]
    # rtdc_total = len([el for el in rel_in_files if ".rtdc" in el])
    # rtdc_processed = 0
    n_files = len(rel_in_files)
    for ind, ff in enumerate(rel_in_files):
        src = path_in / Path(ff)
        dst = path_out / Path(ff)
        dst.parent.mkdir(parents=True, exist_ok=True)
        print("Processing file: " + f"{ind}/{n_files}")
        try:
        # if src.is_file():

        # if src.suffix == '.rtdc':
        #     with dclab.new_dataset(src) as ds:
        #         print(f"Processing File {ff} of length {len(ds)}")
        #         rtdc_processed += 1
        #         print("Processing RTDC-File: " + f"{rtdc_processed}/{rtdc_total}")

            process_file(src, dst, with_basin)
        except KeyboardInterrupt:
            break
        except Exception as e:
            logger.info(f"\n\tERROR Processing File: {ff}\n{e}\n")

# # TODO Do I need this function?
# def update_prediction_of_dir(path_in: Union[str, Path],
#                              model_path: Union[str, Path],
#                              model_name: str = "",
#                              # mlflow: bool = False,
#                              device: str = 'cuda',
#                              num_workers: int = 16,
#                              compute_locally: bool = False,
#                              mean=None,
#                              std=None,
#                              brightness_factor=None
#                              ):
#     def process_file(src):
#         if compute_locally:
#             # Setting up Path
#             src_tmp = Path("tmp_orig.rtdc")
#             # copy data from src to local
#             shutil.copy(src, src_tmp)
#         else:
#             src_tmp = src
#
#         # apply processing script
#         update_prediction(path_in=src_tmp,
#                           # model_path=model_path,
#                           # model_name=model_name,
#                           model=model,
#                           # mlflow=mlflow,
#                           device=device,
#                           num_workers=num_workers,
#                           mean=mean,
#                           std=std,
#                           brightness_factor=brightness_factor,
#                           )
#
#         # copy data from local to dst
#         if compute_locally:
#             shutil.copyfile(src=src_tmp, dst=src)
#             src_tmp.unlink()
#
#     # TODO put it as an argument to process_file()
#     model = OneModel(model_path=model_path, device=device, model_name=model_name)
#
#     path_in = Path(path_in)
#
#     rel_in_files = [os.path.relpath(el, path_in)
#                     for el in path_in.rglob("**/*")]
#     rtdc_files = [el for el in rel_in_files if ".rtdc" in el]
#
#     rtdc_total = len([el for el in rel_in_files if ".rtdc" in el])
#     rtdc_processed = 0
#
#     for ff in rtdc_files:
#         src = path_in / Path(ff)
#         try:
#             with dclab.new_dataset(src) as ds:
#                 logger.info(f"Processing File {ff} of length {len(ds)}")
#             rtdc_processed += 1
#             print("Processing RTDC-File: "
#                   + f"{rtdc_processed}/{rtdc_total}")
#             process_file(src)
#         except KeyboardInterrupt:
#             break
#         except Exception as e:
#             logger.info(f"\n\tERROR Processing File: {ff}\n{e}\n")


def remove_unlabeled_events(src: [str, Path],
                            dst: [str, Path],
                            compression: typing.Optional[str] = None,
                            override: bool = False) -> None:
    """ Removes all unlabeled events from a dataset labeled by DCTag

    After annotating datasets wtih DCTag, some of the events were skipped and
    therefore do not have an `ml_score` assigned to them.
    This function removes these skipped events and stores the reduced dataset
    in `dst`.

    Parameter
    ---------
    src: [str, pathlib.Path]
        Path of the dataset that should be cleaned
    dest: [str, pathlib.Path]
        Path where the cleaned (and thus reduced) dataset should be saved
    """
    src = Path(src)
    dst = Path(dst)

    compression_kwargs = {"compression": compression}

    dst.parent.mkdir(parents=True, exist_ok=True)

    with dclab.new_dataset(src) as ds:
        # If there are no labelled events in the dataset and no `ml_class`
        # then the filtering below will not work and not remove any events in
        # the dataset. Therefore we need to check here if `ml_class` exists
        # and after filtering check, if some events still remained.
        # Edge case 1:
        #     Dataset was not labelled -> no `ml_class`-feature
        #     -> no events removed. Thus we need the Exception below

        if "ml_class" not in ds.features:
            raise DatasetNotLabeledException
        # Filter out the events that have no dctag label assigned during
        # annotation. Here we take a very large arbitrary number as max value
        ds.config["filtering"]["ml_class min"] = 0
        ds.config["filtering"]["ml_class max"] = 1000
        ds.apply_filter()

        # Edge case 2:

        #     Dataset was run through DCTag, but no cell was labelled,
        #     or potentially labelled, but then reset. This will cause the
        #     `ml_class` to exist, but only contain '-1' entries.
        #     This dataset then should not be exported!
        if np.sum(ds.filter.all) == 0:
            warning_text = (f"Dataset at {src=} does not contain any labelled "
                            f"events. No dataset will be output.")
            warnings.warn(warning_text, EmptyLabeledDatasetNotExported)
            logger.info(warning_text)
        else:
            features = ds.features_innate
            ds.export.hdf5(path=dst, features=features,
                           filtered=True,
                           compression_kwargs=compression_kwargs,
                           override=override)


def fill_all_annotation_features(src: [str, Path]) -> None:
    """Adds all remaining ml_score-features to the RT-DC dataset inplace

    Labelling with DCTag only adds those `ml_score` to the RTDC-dataset that
    have been used in the labelling step. This function adds the remaining
    `ml_score` features to the dataset containing only zeros. This is
    currently needed for the training.
    The list of all `ml_score_...`-features can be found in file
    `dcml.definitions.ml_score_to_int.json`.

    Parameter
    ---------
    src: [str, Path]
        Path to the RT-DC file which needs to be filled up with the remaining
        `ml_score_...` features.
    Note
    ----
    This happens **inplace**!
    """
    ml_score_to_int_dict = load_ml_score_to_int()
    with h5py.File(src, "r+") as hf:
        # delete previously computed feature "ml_class"
        # The `ml_class` features in normally an ancillary feature and will not
        # be written to the file when opened.
        # We still need to check if it exists, because one can export the
        # rtdc-file and if `ml_class` is defined in the list of features
        # it will also be written to the new RTDC-file. Writing to that file
        # another `ml_class` might lead to issues (e.g. concatenating
        # instead of replacing the already existing `ml_class`-array)
        try:
            del hf["events"]["ml_class"]
        except Exception as e:
            logger.info(
                f"Exception when deleting `ml_class` for dataset in "
                f"Path: {src}. It might not be an existing feature. "
                f"The remaining ml_score-features will be added anyways! "
                f"Thrown Error:\n{e}")
        arbitrary_feat_name = list(hf["events"].keys())[0]
        dataset_len = len(hf["events"][arbitrary_feat_name])
        emtpy_feat_array = np.zeros(dataset_len)
        for score_name in ml_score_to_int_dict.keys():
            if score_name not in hf["events"].keys():
                hf["events"].create_dataset(score_name,
                                            data=emtpy_feat_array)


# def prepare_annotated_dctag_dataset_for_training(src: [str, Path],
#                                                  dst: [str, Path],
#                                                  override: bool = False
#                                                  ) -> None:
#     """ Prepares annotated datasets frorm DCTag for training in DeepClassifier
#
#     This function wraps around `remove_unlabeled_events` and
#     `fill_all_annotation_features`, executes them in that order and
#     outputs the cleaned file with created `ml_score_`-features
#     to the `dst`-path.
#
#     Parameter
#     ---------
#     src: [str, pathlib.Path]
#         Path of the dataset which needs to be prepared for training
#     dest: [str, pathlib.Path]
#         Path where the prepared dataset will be saved
#     """
#     src = Path(src)
#     dst = Path(dst)
#
#     remove_unlabeled_events(src, dst, override=override)
#     fill_all_annotation_features(src=dst)


# def transfer_feature_to_filtered_dataset(
#         original_ds_path: [str, Path],
#         filtered_ds_path: [str, Path],
#         feature: str) -> None:
#     """Transfers feature from original dataset to its filtered version
#
#     Based on `index_online` this function will write features from the original
#     dataset to its filtered version if the feature does not exist yet.
#     E.g. this can be used for transferring `image_bg` from a parent dataset
#     to its child dataset
#
#     Parameters
#     original_ds_path: [str, Path]
#         Path to original unfiltered dataset
#     filtered_ds_path: [str, Path]
#         Path to filtered dataset
#     feature: str
#         Name of feature which should be transferred
#     """
#     with dclab.new_dataset(original_ds_path) as original_ds, \
#             dclab.new_dataset(filtered_ds_path) as filtered_ds:
#         idxs_online = filtered_ds["index_online"]
#         real_index_od = np.argwhere(np.isin(original_ds["index_online"],
#                                             idxs_online)).ravel()
#         data = original_ds[feature][real_index_od]
#         shape = data[0].shape
#
#     # Update the feature in the filtered_ds_path
#     with dclab.RTDCWriter(filtered_ds_path, mode="replace") as writer:
#         writer.store_feature(feat=feature,
#                              data=data,
#                              shape=shape)
#         logger.info(f"'{feature}' successfully written "
#                     f"to '{filtered_ds_path}'.")


# # TODO remove it? not used
# def predict_mlflow_cell_type_with_basin(path_in: Union[str, Path],
#                                         path_out: Union[str, Path],
#                                         model_path: str,
#                                         model_name: str = "",
#                                         device: str = 'cpu',
#                                         # mlflow: bool = False,
#                                         num_workers: int = 8,
#                                         batch_size: int = 1,
#                                         mean=None,
#                                         std=None,
#                                         brightness_factor=None
#                                         ):
#     """
#     """
#     path_in = Path(path_in)
#     path_out = Path(path_out)
#
#     if path_out.exists():
#         raise FileExistsError(f"File already exists at Path: '{path_out}'!")
#
#     # Copy File to "path_out"-path
#     if not (path_in.resolve() == path_out.resolve()):
#         shutil.copyfile(path_in, path_out)
#
#     logger.info(f"Cell Prediction of {path_in} -- Start Time: {time.ctime()}")
#     logger.info(f"Number of Workers: {num_workers}")
#     logger.info(f"Batch size: {batch_size}")
#
#     model = OneModel(model_path=model_path, device=device, model_name=model_name)
#
#     prediction_probs = get_predictions(ds_path=path_in,
#                                        model=model,
#                                        batch_size=batch_size,
#                                        num_workers=num_workers,
#                                        device=device,
#                                        mean=mean,
#                                        std=std,
#                                        brightness_factor=brightness_factor)
#
#     # Write prediction to dataset
#     logger.info("Writing Predictions to RTDC-Dataset...")
#     with dclab.RTDCWriter(path_out, mode="reset") as writer, \
#             dclab.new_dataset(path_in) as ds_in:
#         # Write predictions to new dataset
#         for idx, feat in enumerate(model.feature_names):
#             writer.store_feature(feat, prediction_probs[:, idx])
#
#         # Write Metadata to new dataset
#         meta = dict(ds_in.config)
#         meta.pop("filtering")
#         writer.store_metadata(meta)
#
#         basin_feats = [el for el in ds_in.features if "ml_score" not in el]
#         writer.store_basin(basin_name="segmentation_and_features",
#                            basin_type="file",
#                            basin_format="hdf5",
#                            basin_locs=[path_in.resolve()],
#                            basin_feats=basin_feats)
#
#     logger.info(f"Cell Prediction of {path_in} -- End Time: {time.ctime()}")
